  # SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
development:
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: d5dnsinu62ier4
    username: fzemaitkavxivt
    password: xKjI68omhTJDFALP_l4yQSSWda
    host: ec2-54-221-223-92.compute-1.amazonaws.com
    port: 5432
    
test:
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: d5dnsinu62ier4
    username: fzemaitkavxivt
    password: xKjI68omhTJDFALP_l4yQSSWda
    host: ec2-54-221-223-92.compute-1.amazonaws.com
    port: 5432

production:
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: d5dnsinu62ier4
    username: fzemaitkavxivt
    password: xKjI68omhTJDFALP_l4yQSSWda
    host: ec2-54-221-223-92.compute-1.amazonaws.com
    port: 5432